### ISSUE TITLE
Connect wirelessly [non-root]

### ISSUE THREAD

**Issue by jixiang-wang** [fusionneur/ethernally#1] opened 2020-10-31 10:08 UTC
I still can't connect to wifi
![image](https://user-images.githubusercontent.com/31286734/97776558-17093d00-1ba4-11eb-8a45-ac15908179f5.png)

**Comment by fusionneur** [comment] 2020-10-31 11:47
It looks like you're not rooted. The script requires phone to be rooted

**Comment by fusionneur** [comment] 2020-10-31 14:02
I will try to adapt it for non rooted devices as well.

**Comment by jixiang-wang** [comment] 2020-10-31 14:12
As you said,  I have no problem with another rooted phone. 
Thanks, I hope it can be applied to non-rooted phones soon.

**Comment by fusionneur** [comment] 2020-10-31 21:20
I added several commits to ease wireless connectivity for non-root devices as well. Can you please re-test and let me know of your experience? Thank you!

**Comment by anishmittal2020** [comment] 2020-11-02 22:58
@fusionneur 

I have non-rooted Android 10 Samsung A70 device. It has USB-C Cable. I have enabled USB Debugging and the wifi was also on. My phone is in the same local network as my laptop. But still I am unable to connect:

```bash
Attempting Wi-Fi connection first..
No WiFi devices detected
socket: null

Trying connection wirelessy via ADB. Please wait...
Connected via adb to WiFi device


Wi-Fi seems to be turned off or ADB debugging not enabled on device.
Could not connect via WiFi, switching to USB mode

Please plug USB cable and enable USB debugging (To unlock the hidden Developer tools/options menu, go to Android Settings > About > Press on 'build number' 7 times. Then go to android settings > developer tools/options and enable USB debugging)

Checking if USB cable is connected and USB debugging enabled..
.................................................................................
```

**Comment by fusionneur** [comment] 2020-11-02 23:43
Can you please try latest beta release? I did some changes to help me figure out what is happening.

**Comment by anishmittal2020** [comment] 2020-11-03 07:31
```bash
Attempting to discover any attached devices..
List of devices attached
* daemon not running; starting now at tcp:5037
* daemon started successfully


There are no WiFi devices automatically detected/attached - as reported by adb.
Disconnecting adb..

Trying last known working device..
There is no last known working device.

socket: null
connected: 0


Wi-Fi seems to be turned off or ADB debugging not enabled on device.
Could not connect via WiFi, switching to USB mode

Please plug USB cable and enable USB debugging (To unlock the hidden Developer tools/options menu, go to Android Settings > About > Press on 'build number' 7 times. Then go to android settings > developer tools/options and enable USB debugging)

Checking if USB cable is connected and USB debugging enabled..
..........................................................................
```

**Comment by fusionneur** [comment] 2020-11-03 09:13
It looks like your device is not being detected. Check usb cable and restart USB debugging (switch off and on again the toggle in settings) while this message is shown:

```
Checking if USB cable is connected and USB debugging enabled..
..........................................................................
```

**Comment by anishmittal2020** [comment] 2020-11-03 10:53
I did what you said, also my phone is charging while being connected with USB to laptop, which has USB 2 and USB 3 ports while my phone has USB C Port. I have a cable from USB C to USB 2.

**Comment by fusionneur** [comment] 2020-11-03 11:05
Can you please tell me which is the output of (while cable plugged and usb debugging enabled):
```
adb devices
adb shell su --command id
adb shell id
```


Also please make sure USB debugging is on:
1. you should have a persistent notification showing "USB debugging connected"
2. In Android Settings > System >Developer options > USB debugging should be toggled ON

**Comment by anishmittal2020** [comment] 2020-11-03 15:49
USB debugging is toggled ON, phone is charging.

```
$ adb devices

List of devices attached

$ adb shell su --command id
error: no devices/emulators found
$ adb shell id
error: no devices/emulators found
```

**Comment by fusionneur** [comment] 2020-11-03 15:59
It looks like a problem with your device in this particular case and your issue is out of the scope for Ethernally.

Do you have the notification showing "USB debugging connected"? You should have been presented with a prompt to accept host fingerprint. Did you accept it?
You could try changing from 'charging' (no data transfer) to PTP mode as described in this guide: https://www.xda-developers.com/quickly-install-adb/

**Comment by anishmittal2020** [comment] 2020-11-03 21:56
> Do you have the notification showing "USB debugging connected"? You should have been presented with a prompt to accept host fingerprint. Did you accept it?
I don't get this option

> You could try changing from 'charging' (no data transfer) to PTP mode as described in this guide: https://www.xda-developers.com/quickly-install-adb/

Yes I have enabled PTP in  `Default USB Configuration`

But I still have the same problem:

```
$ adb devices

List of devices attached

$ adb shell su --command id
error: no devices/emulators found
$ adb shell id
error: no devices/emulators found
``

**Comment by fusionneur** [comment] 2020-11-03 22:18
May I ask your phone model and android version? It's clearly something fishy going on on your device..

**Comment by anishmittal2020** [comment] 2020-11-04 01:15
I have also done correct udev rules setup according to this: - [M0Rf30/android-udev-rules: Android udev rules list aimed to be the most comprehensive on the net](https://github.com/M0Rf30/android-udev-rules/tree/master/)

I have Android 10 from Samsung Galaxy A70.

**Comment by fusionneur** [comment] 2020-11-04 01:42
What linux distro are u running (and kernel version)?

There's something similar here: https://askubuntu.com/questions/863587/adb-device-list-doesnt-show-phone

Indeed it might be an issue with the actual os detecting the phone. Or maybe your cable does not permit data transfer but only charging. Do you have another USB cable to test? Or another phone to test that cable?

**Comment by anishmittal2020** [comment] 2020-11-04 08:45
Ubuntu 20.04
Kernel 5.4.0-52-generic
Bash 5.0.17

May be my cable is faulty. I will let you know when I get another cable.

Thanks!

**Comment by fusionneur** [comment] 2020-11-08 17:50
@anishmittal2020 , @jixiang-wang did you have the chance to test it ?

**Comment by anishmittal2020** [comment] 2020-11-08 18:01
No, I left it for some time, I don't  know when I would test it.

Thanks and Regards

Anish
________________________________

**Comment by jixiang-wang** [comment] 2020-11-08 18:46
Here is my operation:
1. The following is the operation result after connecting usb:

![image](https://user-images.githubusercontent.com/31286734/98481254-f3916280-2233-11eb-91cf-3df05a3f750f.png)


Check the status of the device at this time:

![image](https://user-images.githubusercontent.com/31286734/98481287-29cee200-2234-11eb-8afc-a99a10aabf50.png)

2. Then disconnect the operation result of usb：

![image](https://user-images.githubusercontent.com/31286734/98481329-74505e80-2234-11eb-8aab-4d2408f655bd.png)


Here are my views:
I think there is no problem with your tool. It should be a problem with my mobile phone system. My mobile phone is an android 10 system and unrooted.
I have also tried many times, each time the result is:
As long as the usb is disconnected, the mobile phone cannot be connected via wifi, but when the usb is connected, the mobile phone can be connected via wifi;


Can you understand what I mean?

**Comment by fusionneur** [comment] 2020-11-08 19:42
@jixiang-wang ,just one quick question - what os do you have ?

**Comment by fusionneur** [comment] 2020-11-08 19:51
I pushed a fix for realink error. However it is unrelated with your experience.

**Comment by fusionneur** [comment] 2020-11-08 19:56
Can you please post the log you get when you run ethernally without usb cable connected, just with wifi on?

**Comment by jixiang-wang** [comment] 2020-11-09 08:17
> Can you please post the log when you run ethernally without the usb cable connected, but just with the wifi turned on?
> 
> Use the code from latest commit as it includes the readlink fix. Thanks!

without the usb cable connected,just with the wifi turned on,
run ethernally 

![image](https://user-images.githubusercontent.com/31286734/98515931-cc27ad80-22a6-11eb-8eff-48cf75681d47.png)

**Comment by fusionneur** [comment] 2020-11-09 16:00
What host OS do you have?

**Comment by jixiang-wang** [comment] 2020-11-09 16:20
> What host OS do you have? And adb version (adb --version)

![image](https://user-images.githubusercontent.com/31286734/98567113-87be0100-22ea-11eb-952b-6cca737ebb7b.png)

**Comment by fusionneur** [comment] 2020-11-09 18:43
By any chance did you have android studio opened when you tried the script?

**Comment by fusionneur** [comment] 2020-11-09 18:57
Also can you please retry the script updated in the last commit. It force kills adb server prior to trying to connect. Hopefully it fixes the issue.

**Comment by jixiang-wang** [comment] 2020-11-09 23:57
> Also can you please retry the script updated in the last commit. It force kills adb server prior to trying to connect. Hopefully it fixes the issue.

It doesn't work

![image](https://user-images.githubusercontent.com/31286734/98609884-53b60080-2329-11eb-8f61-3f8886b57ba6.png)


I have an idea:
When I have connected the device via usb and wifi at the same time, as shown below:

![image](https://user-images.githubusercontent.com/31286734/98610185-0a19e580-232a-11eb-95e2-96394865e2d5.png)

Can I just disconnect the USB connection, but not the wifi connection? If so, how do I do it?
Thanks 🙏

**Comment by fusionneur** [comment] 2020-11-10 00:20
You get some really strange behavior :), and I cannot reproduce as I don't have a Mac. Will look into it tommorrow maybe I figure something out..

**Comment by fusionneur** [comment] 2020-11-10 00:22
can you retry right now the script with the usb cable disconnected? It should retry reconnection since adb is still running on 5555. Post log here. Thanks

**Comment by fusionneur** [comment] 2020-11-10 00:26
I found something similar you are experiencing:
https://stackoverflow.com/questions/31817019/adb-over-wifi-killed-off-after-usb-disconnect
https://stackoverflow.com/questions/18824348/unable-to-get-wireless-adb-working-removing-usb-cable-will-disconnect-the-tcpi/18825750

**Comment by fusionneur** [comment] 2020-11-10 00:28
You could also try to allow ADB debugging in charge only mode (not ptp/mtp)

**Comment by jixiang-wang** [comment] 2020-11-10 00:42
> I found something similar you are experiencing:
> https://stackoverflow.com/questions/31817019/adb-over-wifi-killed-off-after-usb-disconnect
> https://stackoverflow.com/questions/18824348/unable-to-get-wireless-adb-working-removing-usb-cable-will-disconnect-the-tcpi/18825750

thanks 👍 
I have solved:
For some reason, connecting the device in Charge only mode solved the problem. Just make sure "Allow ADB debugging in charge only mode" is enabled before connecting the device.
I haven't tried this model before 

https://stackoverflow.com/questions/51904545/adb-over-wifi-connection-is-lost-after-disconnecting-usb/51904546#51904546

**Comment by fusionneur** [comment] 2020-11-10 00:42
"Can I just disconnect the USB connection, but not the wifi connection? If so, how do I do it?"
you do: adb disconnect PKT...
But I doubt that could solve the issue. Please see above.

**Comment by fusionneur** [comment] 2020-11-10 00:54
> > I found something similar you are experiencing:
> > https://stackoverflow.com/questions/31817019/adb-over-wifi-killed-off-after-usb-disconnect
> > https://stackoverflow.com/questions/18824348/unable-to-get-wireless-adb-working-removing-usb-cable-will-disconnect-the-tcpi/18825750
> 
> thanks 👍
> I have solved:
> For some reason, connecting the device in Charge only mode solved the problem. Just make sure "Allow ADB debugging in charge only mode" is enabled before connecting the device.
> I haven't tried this model before
> 
> https://stackoverflow.com/questions/51904545/adb-over-wifi-connection-is-lost-after-disconnecting-usb/51904546#51904546

Oh so glad it finally works for you! Did you try the script again? Does it properly mirror the screen now after eventually disconnecting usb cable?

**Comment by jixiang-wang** [comment] 2020-11-10 00:56
> > > I found something similar you are experiencing:
> > > https://stackoverflow.com/questions/31817019/adb-over-wifi-killed-off-after-usb-disconnect
> > > https://stackoverflow.com/questions/18824348/unable-to-get-wireless-adb-working-removing-usb-cable-will-disconnect-the-tcpi/18825750
> > 
> > 
> > thanks 👍
> > I have solved:
> > For some reason, connecting the device in Charge only mode solved the problem. Just make sure "Allow ADB debugging in charge only mode" is enabled before connecting the device.
> > I haven't tried this model before
> > https://stackoverflow.com/questions/51904545/adb-over-wifi-connection-is-lost-after-disconnecting-usb/51904546#51904546
> 
> Oh so glad it finally works for you! Did you try the script again? Does it properly mirror the screen now after eventually disconnecting usb cable?

👍 
![image](https://user-images.githubusercontent.com/31286734/98613984-6e40a780-2332-11eb-9ce5-b7ce70c9873d.png)

**Comment by fusionneur** [comment] 2020-11-10 00:58
awesome. thanks for testing and helping improve the script

**Comment by fusionneur** [comment] 2020-11-10 11:38
@anishmittal2020 Let me know when you retest with the new cable and with various usb modes MTP/PTP/only charging.
I am going to close this, as the non-root support is implemented and functional. Please open another issue if you still need support.

**Closed** 2020-11-10 11:38 UTC
Labels: High Priority, enhancement, ongoing
